//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLayerProject.ServiceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDto", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.DTO")]
    [System.SerializableAttribute()]
    public partial class UsuarioDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.AnuncioDto[] AnunciosDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.AvaliacaoDto[] AvaliacoesDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.ComentarioDto[] ComentariosDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.AnuncioDto[] AnunciosDto {
            get {
                return this.AnunciosDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnunciosDtoField, value) != true)) {
                    this.AnunciosDtoField = value;
                    this.RaisePropertyChanged("AnunciosDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.AvaliacaoDto[] AvaliacoesDto {
            get {
                return this.AvaliacoesDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.AvaliacoesDtoField, value) != true)) {
                    this.AvaliacoesDtoField = value;
                    this.RaisePropertyChanged("AvaliacoesDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.ComentarioDto[] ComentariosDto {
            get {
                return this.ComentariosDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosDtoField, value) != true)) {
                    this.ComentariosDtoField = value;
                    this.RaisePropertyChanged("ComentariosDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contato {
            get {
                return this.ContatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoField, value) != true)) {
                    this.ContatoField = value;
                    this.RaisePropertyChanged("Contato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((this.TelefoneField.Equals(value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnuncioDto", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.DTO")]
    [System.SerializableAttribute()]
    public partial class AnuncioDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.CategoriaDto CategoriaDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.ComentarioDto[] ComentariosDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.UsuarioDto UsuarioDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.CategoriaDto CategoriaDto {
            get {
                return this.CategoriaDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaDtoField, value) != true)) {
                    this.CategoriaDtoField = value;
                    this.RaisePropertyChanged("CategoriaDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.ComentarioDto[] ComentariosDto {
            get {
                return this.ComentariosDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosDtoField, value) != true)) {
                    this.ComentariosDtoField = value;
                    this.RaisePropertyChanged("ComentariosDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagem {
            get {
                return this.ImagemField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemField, value) != true)) {
                    this.ImagemField = value;
                    this.RaisePropertyChanged("Imagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.UsuarioDto UsuarioDto {
            get {
                return this.UsuarioDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioDtoField, value) != true)) {
                    this.UsuarioDtoField = value;
                    this.RaisePropertyChanged("UsuarioDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvaliacaoDto", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.DTO")]
    [System.SerializableAttribute()]
    public partial class AvaliacaoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.UsuarioDto UsuarioDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.UsuarioDto UsuarioDto {
            get {
                return this.UsuarioDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioDtoField, value) != true)) {
                    this.UsuarioDtoField = value;
                    this.RaisePropertyChanged("UsuarioDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComentarioDto", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.DTO")]
    [System.SerializableAttribute()]
    public partial class ComentarioDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.AnuncioDto AnuncioDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConteudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.UsuarioDto UsuarioDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.AnuncioDto AnuncioDto {
            get {
                return this.AnuncioDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncioDtoField, value) != true)) {
                    this.AnuncioDtoField = value;
                    this.RaisePropertyChanged("AnuncioDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conteudo {
            get {
                return this.ConteudoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConteudoField, value) != true)) {
                    this.ConteudoField = value;
                    this.RaisePropertyChanged("Conteudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.UsuarioDto UsuarioDto {
            get {
                return this.UsuarioDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioDtoField, value) != true)) {
                    this.UsuarioDtoField = value;
                    this.RaisePropertyChanged("UsuarioDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDto", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.DTO")]
    [System.SerializableAttribute()]
    public partial class CategoriaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.AnuncioDto[] AnunciosDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebLayerProject.ServiceUsuario.CategoriaDto[] CategoriasDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.AnuncioDto[] AnunciosDto {
            get {
                return this.AnunciosDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnunciosDtoField, value) != true)) {
                    this.AnunciosDtoField = value;
                    this.RaisePropertyChanged("AnunciosDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebLayerProject.ServiceUsuario.CategoriaDto[] CategoriasDto {
            get {
                return this.CategoriasDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriasDtoField, value) != true)) {
                    this.CategoriasDtoField = value;
                    this.RaisePropertyChanged("CategoriasDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IServiceUsuario")]
    public interface IServiceUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/SalvarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/SalvarUsuarioResponse")]
        void SalvarUsuario(string nome, string email, string senha, string contato, int telefone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/SalvarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/SalvarUsuarioResponse")]
        System.Threading.Tasks.Task SalvarUsuarioAsync(string nome, string email, string senha, string contato, int telefone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ListarTodos", ReplyAction="http://tempuri.org/IServiceUsuario/ListarTodosResponse")]
        WebLayerProject.ServiceUsuario.UsuarioDto[] ListarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ListarTodos", ReplyAction="http://tempuri.org/IServiceUsuario/ListarTodosResponse")]
        System.Threading.Tasks.Task<WebLayerProject.ServiceUsuario.UsuarioDto[]> ListarTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/buscarPorId", ReplyAction="http://tempuri.org/IServiceUsuario/buscarPorIdResponse")]
        WebLayerProject.ServiceUsuario.UsuarioDto buscarPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/buscarPorId", ReplyAction="http://tempuri.org/IServiceUsuario/buscarPorIdResponse")]
        System.Threading.Tasks.Task<WebLayerProject.ServiceUsuario.UsuarioDto> buscarPorIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuarioChannel : WebLayerProject.ServiceUsuario.IServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<WebLayerProject.ServiceUsuario.IServiceUsuario>, WebLayerProject.ServiceUsuario.IServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SalvarUsuario(string nome, string email, string senha, string contato, int telefone) {
            base.Channel.SalvarUsuario(nome, email, senha, contato, telefone);
        }
        
        public System.Threading.Tasks.Task SalvarUsuarioAsync(string nome, string email, string senha, string contato, int telefone) {
            return base.Channel.SalvarUsuarioAsync(nome, email, senha, contato, telefone);
        }
        
        public WebLayerProject.ServiceUsuario.UsuarioDto[] ListarTodos() {
            return base.Channel.ListarTodos();
        }
        
        public System.Threading.Tasks.Task<WebLayerProject.ServiceUsuario.UsuarioDto[]> ListarTodosAsync() {
            return base.Channel.ListarTodosAsync();
        }
        
        public WebLayerProject.ServiceUsuario.UsuarioDto buscarPorId(int id) {
            return base.Channel.buscarPorId(id);
        }
        
        public System.Threading.Tasks.Task<WebLayerProject.ServiceUsuario.UsuarioDto> buscarPorIdAsync(int id) {
            return base.Channel.buscarPorIdAsync(id);
        }
    }
}
