//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLayerProject.ServiceUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IServiceUsuario")]
    public interface IServiceUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/SalvarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/SalvarUsuarioResponse")]
        void SalvarUsuario(string nome, string email, string senha, string contato, int telefone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/SalvarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/SalvarUsuarioResponse")]
        System.Threading.Tasks.Task SalvarUsuarioAsync(string nome, string email, string senha, string contato, int telefone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuarioChannel : WebLayerProject.ServiceUsuario.IServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<WebLayerProject.ServiceUsuario.IServiceUsuario>, WebLayerProject.ServiceUsuario.IServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SalvarUsuario(string nome, string email, string senha, string contato, int telefone) {
            base.Channel.SalvarUsuario(nome, email, senha, contato, telefone);
        }
        
        public System.Threading.Tasks.Task SalvarUsuarioAsync(string nome, string email, string senha, string contato, int telefone) {
            return base.Channel.SalvarUsuarioAsync(nome, email, senha, contato, telefone);
        }
    }
}
